### ISSUE TITLE
API stop working

### ISSUE THREAD

**Issue by rennan0** [diazzaid/whatsapp-api-venom-simple#1]
HI,
Im try to run this API, but a few minutes after it started the API stop working. On the console it still indicates that the api is running, but no message is sent. It is possible to see on the console the arrival of a new POST but the message never arrives.
Any tips to solve this problem?

**Comment by diazzaid** [comment]
> 

i tried it on windows os running normally.
make sure 
headless: true,
useChrome: true,

**Comment by rennan0** [comment]
I already figured out what the problem was. When using whatsapp web the application ended up being disconnected by accident. Sorry for the inconvenience.
